# Generated by Django 4.2 on 2024-10-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='number_image',
            field=models.IntegerField(default=0),
        ),
    ]
