# Generated by Django 4.2 on 2024-10-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_remove_place_description_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='content',
            new_name='description_long',
        ),
    ]
