# Generated by Django 4.2 on 2024-10-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_place_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='number_image',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Номер картинки'),
        ),
    ]
